title:              Jockc blog
email:              jockchiang@163.com
description:        This is my technology sharing.
author:             Jockc
baseurl:            ""
url:                "https://blackrockdigital.github.io"

# Social Profiles
twitter_username:   J_K_ET
github_username:    JockChiang
facebook_username:  peter.jiang.jk
linkedin_username:  jock-chiang-06376284

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
